#index:
#    path: /
#    controller: App\Controller\DefaultController::index

### Profile
profile_resetPassword:
    path: /profile/password
    controller: App\Controller\ProfileController::resetPassword